---
region: "eu-west-1"

component: "cert-manager"

storage_bucket_name: "eth-quest-%{hiera('component')}-storage-%{hiera('deployment_identifier')}"

image_version_key: "metadata/version"

cert_manager_image_repository_state_bucket_name: "%{hiera('storage_bucket_name')}"
cert_manager_image_repository_state_key: "deployment-state/cert-manager-image-repository/default.tfstate"
